function vehicle = Ego_vehicle(actorID,position,velocity,roll,pitch,yaw,angularVelocity)

vehicle = struct(...
    'ActorID', actorID, ...
    'Position', [position(1) position(2) 0], ...
    'Velocity', [velocity(1) velocity(2) 0], ...
    'Roll', roll, ...
    'Pitch', pitch, ...
    'Yaw', yaw, ...
    'AngularVelocity', [0 0 angularVelocity]);
end